# Generated by Django 3.2 on 2026-02-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_wildlifeplace_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifeplace',
            name='photo',
        ),
        migrations.AddField(
            model_name='wildlifeplace',
            name='latitute',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifeplace',
            name='longitude',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
