# Generated by Django 3.2 on 2026-02-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20260205_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifeplace',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
