# Generated by Django 3.2 on 2026-02-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_wildlifeplace_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
