# Generated by Django 3.2 on 2026-02-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_guide_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='AGENT',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.agent'),
            preserve_default=False,
        ),
    ]
