# Generated by Django 3.2 on 2026-02-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_guide_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='AGENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.agent'),
        ),
    ]
