# Generated by Django 3.2 on 2026-02-07 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_guide_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUIDE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guide')),
                ('PACKAGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package')),
            ],
        ),
    ]
