# Generated by Django 3.2 on 2026-02-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_assign_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_package',
            name='status',
            field=models.CharField(default='assigned', max_length=20),
        ),
    ]
