# Generated by Django 3.2 on 2026-02-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_assign_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_package',
            name='date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
