# Generated by Django 3.2 on 2026-02-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_assign_package_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='booked_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='from_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='to_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
